name: deploy to untitled-document.net
on: 
  push:
    branches:
      - main  # or your default branch name
  # Enable manual triggers from VS Code
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    # Add environment variables at job level
    env:
      DEPLOY_PATH: untitled-document.net/public_html

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v43

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        mkdir dist
        # Set locale to handle UTF-8 characters
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        
        for file in ${ALL_CHANGED_FILES}; do
          # Remove the iconv conversion since we want to preserve UTF-8 characters
          DIR="$(dirname "${file}")"
          FILE="$(basename "${file}")"
          echo "Processing: [${DIR}] [${FILE}]"  
          mkdir -p "dist/${DIR}"
          cp "${file}" "dist/${DIR}/${FILE}"
        done
        touch dist/commit_time.txt

    - name: Upload to untitled-document.net ftp
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist"
        remoteDir: ${{ env.DEPLOY_PATH }}
    
